FROM rustlang/rust:nightly-bookworm

WORKDIR '/test'
RUN apt update
RUN apt install libseccomp-dev
COPY . .
RUN cargo install --path .
RUN cargo build
RUN rustup component add rust-src
RUN curl -L https://github.com/rust-lang/rust-analyzer/releases/latest/download/rust-analyzer-x86_64-unknown-linux-gnu.gz | gunzip -c - > ./rust-analyzer
RUN chmod +x ./rust-analyzer
RUN echo lol > ./lol.txt
CMD testchamber cat ./lol.txt
ENTRYPOINT ["./rust-analyzer"]
